// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcCnwdUCckPrdkRQpYlMHH8wBNkUb2eu0',
    appId: '1:180950882444:web:d7a7c96b2b35c8091103a9',
    messagingSenderId: '180950882444',
    projectId: 'my-flutter-project-a57a0',
    authDomain: 'my-flutter-project-a57a0.firebaseapp.com',
    databaseURL: 'https://my-flutter-project-a57a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutter-project-a57a0.firebasestorage.app',
    measurementId: 'G-DTS66274VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLGpC2p8Zyn6UPSmGgC0HjHQmETzBWqQU',
    appId: '1:180950882444:android:7f13d0b67e5b179d1103a9',
    messagingSenderId: '180950882444',
    projectId: 'my-flutter-project-a57a0',
    databaseURL: 'https://my-flutter-project-a57a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutter-project-a57a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1BWiGF2SfcKWxGeR6u99HbYCZkKYt4E',
    appId: '1:180950882444:ios:fc587e7d83e1217f1103a9',
    messagingSenderId: '180950882444',
    projectId: 'my-flutter-project-a57a0',
    databaseURL: 'https://my-flutter-project-a57a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutter-project-a57a0.firebasestorage.app',
    iosClientId: '180950882444-g2m1o3l3lqo0c7gcb29auubqfhd1obmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC1BWiGF2SfcKWxGeR6u99HbYCZkKYt4E',
    appId: '1:180950882444:ios:fc587e7d83e1217f1103a9',
    messagingSenderId: '180950882444',
    projectId: 'my-flutter-project-a57a0',
    databaseURL: 'https://my-flutter-project-a57a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutter-project-a57a0.firebasestorage.app',
    iosClientId: '180950882444-g2m1o3l3lqo0c7gcb29auubqfhd1obmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcCnwdUCckPrdkRQpYlMHH8wBNkUb2eu0',
    appId: '1:180950882444:web:dbce16bc7f2a1d7a1103a9',
    messagingSenderId: '180950882444',
    projectId: 'my-flutter-project-a57a0',
    authDomain: 'my-flutter-project-a57a0.firebaseapp.com',
    databaseURL: 'https://my-flutter-project-a57a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutter-project-a57a0.firebasestorage.app',
    measurementId: 'G-5E5EPLJ4PD',
  );
}
